# Only used in X11 sessions. Motion is already accelerated on the ThinkPad.
Section "InputClass"
    Identifier "tpkbd pointer"
    MatchProduct "ThinkPad remote pointer"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
EndSection
